name: Publish Cindy Plugins (Dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-dev:
    name: Publish plugins to dev
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-cindy-plugins.yml
    with:
      deployment_name: dev
      plugin_server_url: https://plugin-dev.cindy.com.cn
      event_name: ${{ github.event_name }}
      before_sha: ${{ github.event.before }}
      after_sha: ${{ github.sha }}
